api_version = "2025-01"

[[extensions]]

uid = "897ada22-1e96-7904-586f-36a36869cbc89642265a"

type = "ui_extension"
name = "INK Delivery Protection"
handle = "ink-checkout-disclosure"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"
